# Generated by Django 4.0.10 on 2024-03-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_emailadress_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
