# Generated by Django 4.0.10 on 2024-04-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_mail_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailadress',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='mail',
            name='emailadress_id',
        ),
        migrations.RemoveField(
            model_name='re',
            name='mail_id',
        ),
        migrations.RemoveField(
            model_name='to',
            name='emailadress_id',
        ),
        migrations.RemoveField(
            model_name='to',
            name='mail_id',
        ),
        migrations.DeleteModel(
            name='Cc',
        ),
        migrations.DeleteModel(
            name='Emailadress',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='Mail',
        ),
        migrations.DeleteModel(
            name='Re',
        ),
        migrations.DeleteModel(
            name='To',
        ),
    ]
