# Generated by Django 4.0.10 on 2024-04-12 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Re',
        ),
    ]
